name: glados mirror repo

on:
  push:
    branches: ["main", "CI/CD"]
  pull_request:
    branches: ["main"]
    types: ["closed"]

jobs:
  push-mirror:
    if: ${{ github.repository == 'HajarAhazzam/glados' && (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged)) }}
    runs-on: ubuntu-latest
    name: push-mirror

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: "git@github.com:EpitechPGE3-2025/G-FUN-500-PAR-5-2-glados-4.git"
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
