name: Release

on:
  push:
    branches :
      - main
      - dev
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        default: false
        description: "test release sans publier"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Haskell + Stack
        uses: haskell/actions/setup@v2
        with:
          enable-stack: true

      - name: Cache Stack
        uses: actions/cache@v4
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - name: Build fresh release (make re)
        run: make re

      - name: Check binary exists
        run: ls -l ./glados

      - name: Create zip archive
        run: zip glados.zip glados
        # utiliser variable GITHUB_REF pour obtenir le nom du tag (pour que soit + propre) run: zip glados-${GITHUB_REF#refs/tags/}.zip glados 

      - name: Create GitHub Release
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && inputs.dry-run == false }}
        uses: softprops/action-gh-release@v2
        with:
          files: ./glados.zip
        env:
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}

      - name: Upload zip as artifact
        if: ${{ github.event_name != 'push' }}
        uses: actions/upload-artifact@v4
        with:
          name: glados-zip-test
          path: ./glados.zip



          ## usage: git tag v0.1.0-test et git push origin v0.1.0-test
