name: Release

on:
  push:
    branches:
      - main
      - dev
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write   # pour pouvoir create release

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Haskell + Stack
        uses: haskell/actions/setup@v2
        with:
          enable-stack: true

      - name: Cache Stack
        uses: actions/cache@v4
        with:
          path: |
            ~/.stack
            inklusif/.stack-work
            vm/.stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('inklusif/stack.yaml', 'inklusif/stack.yaml.lock', 'inklusif/package.yaml', 'inklusif/**/*.cabal', 'vm/stack.yaml', 'vm/stack.yaml.lock', 'vm/package.yaml', 'vm/**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - name: Build compiler (make re)
        run: make re
        working-directory: inklusif

      - name: Build vm (make re)
        run: make re
        working-directory: vm

      - name: Check binaries exist
        run: |
          ls -l inklusif/glados
          ls -l vm/glados-vm

      - name: Create zip archive
        run: |
          zip -r glados-${{ github.ref_name }}.zip inklusif/glados vm/glados-vm
          unzip -l glados-${{ github.ref_name }}.zip

      - name: Create GitHub Release
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && github.event.inputs.dry-run != 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          files: ./glados-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload zip as artifact (dry-run / manual)
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run == true }}
        uses: actions/upload-artifact@v4
        with:
          name: glados-zip-test
          path: ./glados-${{ github.ref_name }}.zip
