name: Sync
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  pull-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror Pull
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          source_repo_url: "git@github.com:EpitechPGE3-2025/G-FUN-500-PAR-5-2-glados-4.git"
          target_repo_url: "git@github.com:HajarAhazzam/glados.git"
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          force_update: true